# -*- coding: utf-8 -*-
"""Transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-bcbS76eGwFVelxlI22wxddO1WREXso
"""

! pip install transformers

from transformers import pipeline
classifier=pipeline("sentiment-analysis")
classifier("good luck")

classifier("This camera is not a bad choice for anyone who dislikes blurry photos.")

classifier1=pipeline("zero-shot-classification")
classifier1(
    "csk loss this season but everyone taking ad-shooting to promote the product",
    candidate_labels=["education","sports","business","politics"]
)

generator=pipeline("text-generation",model="JetBrains/Mellum2-12B-A2.5B-Instruct")
generator("Dhoni will continue ",
          max_length=60,
          num_return_sequences=2)